name: task-scheduler
services:
- name: web
  source_dir: /
  github:
    repo: kunalsachdev06/Mini-Task-Scheduler
    branch: main
  run_command: npm start
  build_command: npm install
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: JWT_SECRET
    value: YOUR_SECURE_JWT_SECRET_HERE
    type: SECRET
  - key: VAPID_PUBLIC_KEY
    value: YOUR_VAPID_PUBLIC_KEY
    type: SECRET
  - key: VAPID_PRIVATE_KEY
    value: YOUR_VAPID_PRIVATE_KEY
    type: SECRET
  - key: VAPID_EMAIL
    value: your-email@yourdomain.com