# Alertmanager Configuration for Task Scheduler
# Handles alert routing, grouping, and notification delivery

global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@yourdomain.com'
  smtp_auth_username: 'alerts@yourdomain.com'
  smtp_auth_password: 'your-app-specific-password'

# Templates for alert notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route tree for alert organization
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'default-receiver'
  
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 10s
      repeat_interval: 5m
      continue: true

    # Security alerts - immediate notification
    - match:
        category: security
      receiver: 'security-alerts'
      group_wait: 10s
      repeat_interval: 1h
      continue: true

    # Database alerts
    - match:
        service: database
      receiver: 'database-alerts'
      group_interval: 2m
      repeat_interval: 30m

    # Performance alerts
    - match:
        category: performance
      receiver: 'performance-alerts'
      group_interval: 10m
      repeat_interval: 2h

    # SSL certificate alerts
    - match:
        alertname: SSLCertExpiring
      receiver: 'ssl-alerts'
      repeat_interval: 24h

# Notification receivers
receivers:
  # Default receiver for general alerts
  - name: 'default-receiver'
    email_configs:
      - to: 'admin@yourdomain.com'
        subject: '[Task Scheduler] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

  # Critical alerts - multiple channels
  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@yourdomain.com, devops@yourdomain.com'
        subject: '🚨 CRITICAL: [Task Scheduler] {{ .GroupLabels.alertname }}'
        body: |
          🚨 CRITICAL ALERT 🚨
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Instance: {{ .Labels.instance }}
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          
          Dashboard: https://grafana.yourdomain.com/d/taskscheduler
          Runbook: {{ .Annotations.runbook_url }}
          {{ end }}
    
    # Slack notification for critical alerts
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts-critical'
        title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Instance:* {{ .Labels.instance }}
          *Started:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
        send_resolved: true

    # Discord notification for critical alerts
    discord_configs:
      - webhook_url: 'https://discord.com/api/webhooks/YOUR/DISCORD/WEBHOOK'
        title: '🚨 Critical Alert'
        description: |
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Severity:** {{ .Labels.severity }}
          **Instance:** {{ .Labels.instance }}
          **Started:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

  # Security alerts - specialized handling
  - name: 'security-alerts'
    email_configs:
      - to: 'security@yourdomain.com, admin@yourdomain.com'
        subject: '🔒 SECURITY ALERT: [Task Scheduler] {{ .GroupLabels.alertname }}'
        body: |
          🔒 SECURITY ALERT 🔒
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Source IP: {{ .Labels.source_ip }}
          Instance: {{ .Labels.instance }}
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          
          Immediate action may be required.
          Security Dashboard: https://grafana.yourdomain.com/d/security
          {{ end }}

  # Database alerts
  - name: 'database-alerts'
    email_configs:
      - to: 'dba@yourdomain.com, admin@yourdomain.com'
        subject: '💾 Database Alert: [Task Scheduler] {{ .GroupLabels.alertname }}'
        body: |
          💾 DATABASE ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Database: {{ .Labels.database }}
          Instance: {{ .Labels.instance }}
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

  # Performance alerts
  - name: 'performance-alerts'
    email_configs:
      - to: 'devops@yourdomain.com'
        subject: '⚡ Performance Alert: [Task Scheduler] {{ .GroupLabels.alertname }}'
        body: |
          ⚡ PERFORMANCE ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Metric: {{ .Labels.metric }}
          Value: {{ .Labels.value }}
          Instance: {{ .Labels.instance }}
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

  # SSL certificate alerts
  - name: 'ssl-alerts'
    email_configs:
      - to: 'admin@yourdomain.com'
        subject: '🔐 SSL Certificate Alert: [Task Scheduler] {{ .GroupLabels.alertname }}'
        body: |
          🔐 SSL CERTIFICATE ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Domain: {{ .Labels.domain }}
          Days until expiry: {{ .Labels.days_until_expiry }}
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          
          Please renew the certificate before it expires.
          {{ end }}

# Inhibition rules to reduce noise
inhibit_rules:
  # Inhibit non-critical alerts when critical alerts are firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

  # Inhibit duplicate alerts
  - source_match:
      alertname: 'InstanceDown'
    target_match_re:
      alertname: '.*'
    equal: ['instance']